exp_name: iccad13

defaults:
  - dataset: iccad13_data

hydra:
  run:
    dir: ${exp_name}_outputs

basic_path: /home/guojin/projects/develset_opc/levelset_net/

kernel:
  npy_path: ${basic_path}/kernels
  opt_kernel: ${kernel.npy_path}/optKernel.npy
  opt_kernel_scale: ${kernel.npy_path}/optKernel_scale.npy
  combo_opt_kernel: ${kernel.npy_path}/comboOptKernel.npy
  num_kernel_used: 24 # min: 1 max: 24

trainer:
  gpus: 1
  max_epochs: 30

logger:
  refresh: True # delete old logs
  save_path: tb_loggers
  log_metrics: True

view:
  save_img: False
  save_img_last_epochs: 1
  save_loss : True

model:
  loss:
    ilt_weight: 1
    pvb_weight: 0.3
  ckpt:
    save_time: ${now:%Y-%m-%d_%H-%M-%S}
    save_path: ckpts_${model.ckpt.save_time}