exp_name: iccad13

defaults:
  - dataset: unet320_data

hydra:
  run:
    dir: ${exp_name}_outputs

basic_path:  ${hydra:runtime.cwd}

trainer:
  gpus: 1
  max_epochs: 30

logger:
  refresh: True # delete old logs
  save_path: tb_loggers
  log_metrics: True

view:
  save_img: True
  save_img_last_epochs: 30
  save_loss : True

model:
  loss_weights:
    ilt_weight: 1
    pvb_weight: 7
  ilt_exp: 4 # the loss for ilt exponent (target - nominal)^(ilt_exp), must be int
  ckpt:
    save_time: ${now:%Y-%m-%d_%H-%M-%S}
    save_path: ckpts_${model.ckpt.save_time}
  add_curv: False  # add curveture term
  curv_weight: 1
  # add_curv: False
  torch_fft: False # use the torch original fft?

kernel:
  npy_path: ${basic_path}/kernels/np
  opt_kernel: ${kernel.npy_path}/optKernel.npy
  opt_kernel_scale: ${kernel.npy_path}/optKernel_scale.npy
  combo_opt_kernel: ${kernel.npy_path}/comboOptKernel.npy
  num_kernel_used: 8 # min: 1 max: 24